### ISSUE TITLE
Time zone

### ISSUE THREAD

**Issue by PaulOckenden** [cschwer/googleDocsLogging#3]
All seems to be working well. But I'm in the UK and I'm seeing times that are several hours out.

I assume it's a time-zone thing?

**Comment by PaulOckenden** [comment]
Sussed it - the spreadsheet which you copy in step 2 has an embedded timezone. You need to go to File / Spreadsheet Settings, from where you can adjust both the locale and timezone.

It won't recalculate data up to that point, but any new entries after that point will have the correct time.

Might be worth adding a note in the instructions to do this?

**Comment by cschwer** [comment]
I added  step 3a to let people know to change the timezone.  Thanks!
